import { useEffect, useState } from "react";
import MainLayout from "../layouts/MainLayout";
import api from "../api/api";

function Alerts() {
  const [alerts, setAlerts] = useState([]);
  const [search, setSearch] = useState("");
  const [severity, setSeverity] = useState("All");
  const [loading, setLoading] = useState(true);

  const fetchAlerts = async () => {
    try {
      const response = await api.get("/notifications/");
      setAlerts(response.data);
    } catch (error) {
      console.error("Failed to fetch alerts:", error);
    } finally {
      setLoading(false);
    }
  };

  const markAsRead = async (id) => {
    try {
      await api.put(`/notifications/${id}/read`);

      setAlerts((prev) =>
        prev.map((alert) =>
          alert._id === id
            ? { ...alert, read: true }
            : alert
        )
      );
    } catch (error) {
      console.error(error);
    }
  };

  const deleteAlert = async (id) => {
    if (!window.confirm("Delete this alert?")) return;

    try {
      await api.delete(`/notifications/${id}`);

      setAlerts((prev) =>
        prev.filter((alert) => alert._id !== id)
      );
    } catch (error) {
      console.error(error);
    }
  };

  useEffect(() => {
    fetchAlerts();

    const interval = setInterval(fetchAlerts, 30000);

    return () => clearInterval(interval);
  }, []);

  const filteredAlerts = alerts.filter((alert) => {
    const matchesSearch =
      alert.title.toLowerCase().includes(search.toLowerCase());

    const matchesSeverity =
      severity === "All" || alert.severity === severity;

    return matchesSearch && matchesSeverity;
  });

  return (
    <MainLayout>
      <h1 className="text-4xl text-white font-bold">
        Security Alerts
      </h1>

      <p className="text-gray-400 mt-2">
        Latest alerts generated by the monitoring engine.
      </p>

      <div className="flex gap-4 mt-8">
        <input
          type="text"
          placeholder="Search Alerts..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          className="bg-gray-800 text-white px-4 py-3 rounded-lg w-80"
        />

        <select
          value={severity}
          onChange={(e) => setSeverity(e.target.value)}
          className="bg-gray-800 text-white px-4 py-3 rounded-lg"
        >
          <option>All</option>
          <option>Critical</option>
          <option>High</option>
          <option>Medium</option>
          <option>Low</option>
        </select>
      </div>

      <div className="mt-8 bg-gray-900 rounded-xl overflow-hidden">
        <table className="w-full">
          <thead className="bg-gray-800">
            <tr>
              <th className="text-left text-white p-4">Title</th>
              <th className="text-left text-white p-4">Severity</th>
              <th className="text-left text-white p-4">Time</th>
              <th className="text-left text-white p-4">Status</th>
              <th className="text-left text-white p-4">Actions</th>
            </tr>
          </thead>

          <tbody>
            {loading ? (
              <tr>
                <td
                  colSpan="5"
                  className="text-center text-gray-400 p-6"
                >
                  Loading...
                </td>
              </tr>
            ) : filteredAlerts.length === 0 ? (
              <tr>
                <td
                  colSpan="5"
                  className="text-center text-gray-400 p-6"
                >
                  No alerts found.
                </td>
              </tr>
            ) : (
              filteredAlerts.map((alert) => (
                <tr
                  key={alert._id}
                  className="border-b border-gray-800"
                >
                  <td className="text-white p-4">
                    {alert.title}
                  </td>

                  <td className="text-white p-4">
                    {alert.severity}
                  </td>

                  <td className="text-gray-400 p-4">
                    {new Date(alert.timestamp).toLocaleString()}
                  </td>

                  <td className="p-4">
                    {alert.read ? (
                      <span className="text-green-400">
                        Read
                      </span>
                    ) : (
                      <span className="text-red-400">
                        New
                      </span>
                    )}
                  </td>

                  <td className="p-4 flex gap-2">
                    {!alert.read && (
                      <button
                        onClick={() => markAsRead(alert._id)}
                        className="bg-blue-600 hover:bg-blue-700 text-white px-3 py-1 rounded"
                      >
                        Read
                      </button>
                    )}

                    <button
                      onClick={() => deleteAlert(alert._id)}
                      className="bg-red-600 hover:bg-red-700 text-white px-3 py-1 rounded"
                    >
                      Delete
                    </button>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
    </MainLayout>
  );
}

export default Alerts;